name: build image

on:
  push:
    tags:
    - 'rule-v[0-9].[0-9]+.[0-9]+**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup make
        run: make setup
      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push image to ACR
        run: |
          make build
          GIT_TAG=${GITHUB_REF#refs/tags/}
          docker build --no-cache -t registry.cn-beijing.aliyuncs.com/llaoj/harbor-scanner-trivy:${GIT_TAG} .
          docker push registry.cn-beijing.aliyuncs.com/llaoj/harbor-scanner-trivy:${GIT_TAG}